//! Narrow internal commands. No plugin build/release/scaffolding or PR execution.
use crate::{
    RegistryError, RegistryResult, RegistrySourceV1, generate_catalog,
    git_data::{
        PrDataReader, read_catalog_git, read_regular, read_snapshot_git, validate_revision,
    },
    read_source_directory,
    schema_export::generated_contracts,
    transport::ArtifactClient,
};
use chronlyt_plugin_contracts::{PluginCatalogV1, limits::MAX_CATALOG_BYTES};
use std::{
    collections::BTreeMap,
    ffi::OsString,
    fs,
    io::Write,
    path::{Path, PathBuf},
};

enum Operation {
    Schemas {
        write: bool,
    },
    Generate {
        source: PathBuf,
        base: PathBuf,
        base_rev: String,
    },
    CheckGit {
        source: PathBuf,
        revision: String,
        base: PathBuf,
        base_rev: String,
    },
    CheckPr {
        number: u64,
        revision: String,
        base: PathBuf,
        base_rev: String,
    },
}

fn parse(args: Vec<OsString>) -> RegistryResult<Operation> {
    let bad = || RegistryError::Invalid("command arguments; see docs/registry.md");
    let Some(command) = args.first().and_then(|s| s.to_str()) else {
        return Err(bad());
    };
    if command == "schemas" {
        return match args.get(1).and_then(|s| s.to_str()) {
            Some("--write") if args.len() == 2 => Ok(Operation::Schemas { write: true }),
            Some("--check") if args.len() == 2 => Ok(Operation::Schemas { write: false }),
            _ => Err(bad()),
        };
    }
    if !matches!(command, "generate" | "check") || args.len() % 2 != 1 {
        return Err(bad());
    }
    let mut options = BTreeMap::new();
    for pair in args[1..].as_chunks::<2>().0 {
        let key = pair[0].to_str().ok_or_else(bad)?;
        if options.insert(key, pair[1].clone()).is_some() {
            return Err(bad());
        }
    }
    let base: PathBuf = options.remove("--base-git").ok_or_else(bad)?.into();
    let base_rev = options
        .remove("--base-rev")
        .ok_or_else(bad)?
        .into_string()
        .map_err(|_| bad())?;
    validate_revision(&base_rev)?;
    let operation = if command == "generate" {
        Operation::Generate {
            source: options.remove("--source-dir").ok_or_else(bad)?.into(),
            base,
            base_rev,
        }
    } else {
        let revision = options
            .remove("--source-rev")
            .ok_or_else(bad)?
            .into_string()
            .map_err(|_| bad())?;
        validate_revision(&revision)?;
        if let Some(source) = options.remove("--source-git") {
            Operation::CheckGit {
                source: source.into(),
                revision,
                base,
                base_rev,
            }
        } else {
            let text = options
                .remove("--source-pr")
                .ok_or_else(bad)?
                .into_string()
                .map_err(|_| bad())?;
            let number: u64 = text.parse().map_err(|_| bad())?;
            if number == 0 || number > i32::MAX as u64 || number.to_string() != text {
                return Err(bad());
            }
            Operation::CheckPr {
                number,
                revision,
                base,
                base_rev,
            }
        }
    };
    if !options.is_empty() {
        return Err(bad());
    }
    Ok(operation)
}

fn baseline(
    root: &Path,
    revision: &str,
    source: &RegistrySourceV1,
) -> RegistryResult<PluginCatalogV1> {
    match read_catalog_git(root, revision)? {
        Some(bytes) => Ok(PluginCatalogV1::parse(&bytes)?),
        // Initial bootstrap only. Missing is distinct from invalid or unsafe.
        None if source.records.is_empty() => Ok(PluginCatalogV1 {
            schema_version: 1,
            generated_at: source.metadata.generated_at.clone(),
            plugins: vec![],
        }),
        None => Err(RegistryError::Invalid(
            "base catalog required for nonempty registry",
        )),
    }
}

fn compare(actual: &[u8], generated: &[u8]) -> RegistryResult<()> {
    if actual != generated {
        return Err(RegistryError::Invalid("generated bytes differ"));
    }
    Ok(())
}

fn write_atomic(path: &Path, bytes: &[u8]) -> RegistryResult<()> {
    match fs::symlink_metadata(path) {
        Ok(_) => {
            read_regular(path, MAX_CATALOG_BYTES)?;
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(_) => return Err(RegistryError::Io),
    }
    let parent = path
        .parent()
        .ok_or(RegistryError::Invalid("output directory"))?;
    let mut output = tempfile::NamedTempFile::new_in(parent)?;
    output.write_all(bytes)?;
    output.as_file().sync_all()?;
    output.persist(path).map_err(|_| RegistryError::Io)?;
    Ok(())
}

fn schemas(write: bool) -> RegistryResult<()> {
    // Source location belongs to the trusted tool build, never a registry field.
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()?;
    let mut directory = root;
    for name in ["contracts", "generated", "v1"] {
        directory.push(name);
        if write && !directory.try_exists()? {
            fs::create_dir(&directory)?;
        }
        let meta = fs::symlink_metadata(&directory)?;
        if !meta.is_dir() || meta.file_type().is_symlink() {
            return Err(RegistryError::Invalid("schema directory"));
        }
    }
    for (name, bytes) in generated_contracts()? {
        let path = directory.join(name);
        if write {
            write_atomic(&path, &bytes)?;
        } else {
            compare(&read_regular(&path, MAX_CATALOG_BYTES)?, &bytes)?;
        }
    }
    Ok(())
}

pub fn run(args: Vec<OsString>) -> RegistryResult<()> {
    match parse(args)? {
        Operation::Schemas { write } => schemas(write),
        Operation::Generate {
            source,
            base,
            base_rev,
        } => {
            let records = read_source_directory(&source)?;
            let previous = baseline(&base, &base_rev, &records)?;
            let bytes = generate_catalog(&records, &previous, &mut ArtifactClient::new()?)?;
            write_atomic(&source.join("catalog.json"), &bytes)
        }
        Operation::CheckGit {
            source,
            revision,
            base,
            base_rev,
        } => {
            let data = read_snapshot_git(&source, &revision)?;
            let previous = baseline(&base, &base_rev, &data.source)?;
            let bytes = generate_catalog(&data.source, &previous, &mut ArtifactClient::new()?)?;
            compare(&data.catalog_bytes, &bytes)
        }
        Operation::CheckPr {
            number,
            revision,
            base,
            base_rev,
        } => {
            let mut reader = PrDataReader::new()?;
            let data = reader.read(number, &revision)?;
            reader.verify_freshness(&data, &base_rev)?;
            let previous = baseline(&base, &base_rev, &data.source)?;
            let bytes = generate_catalog(&data.source, &previous, &mut ArtifactClient::new()?)?;
            compare(&data.catalog_bytes, &bytes)?;
            reader.verify_freshness(&data, &base_rev)?;
            use sha2::{Digest, Sha256};
            println!(
                "registry-proof version=1 trusted_sha={} pr={} head_sha={} catalog_sha256={:x}",
                base_rev,
                data.pr_number(),
                data.head_sha,
                Sha256::digest(&bytes)
            );
            Ok(())
        }
    }
}
